[package]
name = "bevy-ray-casting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_prototype_lyon = "0.5"
bevy_svg = "0.7"
quick-xml = "0.23.0"